In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import boxcox

pd.options.display.max_rows = 100

In [69]:
file1 = pd.read_csv('datei1.csv')
file2 = pd.read_csv('datei2.csv')

In [70]:
ca_df = pd.concat([file1,file2],axis = 0, sort=False)

In [71]:
ca_df = ca_df.reset_index(drop=True)

In [72]:
ca_df

,state,gender,education,CLV,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...
4999,Arizona,M,Master,847141.75%,63513.0,70.0,1/0/00,Personal Auto,Four-Door Car,185.667213
5000,Arizona,F,College,543121.91%,58161.0,68.0,1/0/00,Corporate Auto,Four-Door Car,140.747286
5001,Nevada,F,College,568964.41%,83640.0,70.0,1/0/00,Corporate Auto,Two-Door Car,471.050488
5002,California,F,Master,368672.38%,0.0,96.0,1/0/00,Personal Auto,Two-Door Car,28.460568
5003,California,M,Bachelor,399258.39%,0.0,111.0,1/0/00,Personal Auto,SUV,700.349052